### ISSUE TITLE
Error: Call to a member function getMethodInstance()

### ISSUE THREAD

**Issue by jorgb90** [bitpay/bitpay-checkout-magento2#67]
```
[2022-11-07T10:12:41.382829+00:00] main.CRITICAL: Error: Call to a member function getMethodInstance() on null in /public_html/vendor/bitpay/module-bpcheckout/Model/BPRedirect.php:80
Stack trace:
#0 /public_html/vendor/bitpay/module-bpcheckout/Plugin/Onepage/SuccessPlugin.php(21): Bitpay\BPCheckout\Model\BPRedirect->execute()
#1 /public_html/vendor/magento/framework/Interception/Interceptor.php(146): Bitpay\BPCheckout\Plugin\Onepage\SuccessPlugin->afterExecute()
#2 /public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Controller\Onepage\Success\Interceptor->Magento\Framework\Interception\{closure}()
#3 /public_html/generated/code/Magento/Checkout/Controller/Onepage/Success/Interceptor.php(23): Magento\Checkout\Controller\Onepage\Success\Interceptor->___callPlugins()
#4 /public_html/vendor/magento/framework/App/Action/Action.php(111): Magento\Checkout\Controller\Onepage\Success\Interceptor->execute()
#5 /public_html/vendor/magento/module-checkout/Controller/Onepage.php(161): Magento\Framework\App\Action\Action->dispatch()
#6 /public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Controller\Onepage->dispatch()
#7 /public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Controller\Onepage\Success\Interceptor->___callParent()
#8 /public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Controller\Onepage\Success\Interceptor->Magento\Framework\Interception\{closure}()
#9 /public_html/generated/code/Magento/Checkout/Controller/Onepage/Success/Interceptor.php(32): Magento\Checkout\Controller\Onepage\Success\Interceptor->___callPlugins()
#10 /public_html/vendor/magento/framework/App/FrontController.php(245): Magento\Checkout\Controller\Onepage\Success\Interceptor->dispatch()
#11 /public_html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#12 /public_html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#13 /public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#14 /public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#15 /public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#16 /public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#17 /public_html/vendor/mirasvit/module-push-notification/src/PushNotification/Plugin/Framework/App/FrontController/FirebaseServerWorkerJsResponsePlugin.php(74): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#18 /public_html/vendor/magento/framework/Interception/Interceptor.php(135): Mirasvit\PushNotification\Plugin\Framework\App\FrontController\FirebaseServerWorkerJsResponsePlugin->aroundDispatch()
#19 /public_html/vendor/mirasvit/module-cache-warmer/src/CacheWarmer/Plugin/Debug/OnHitPlugin.php(145): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#20 /public_html/vendor/magento/framework/Interception/Interceptor.php(135): Mirasvit\CacheWarmer\Plugin\Debug\OnHitPlugin->aroundAroundDispatch()
#21 /public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->Magento\Framework\Interception\{closure}()
#22 /public_html/generated/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin/Interceptor.php(23): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callPlugins()
#23 /public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->aroundDispatch()
#24 /public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#25 /public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#26 /public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#27 /public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#28 /public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#29 /public_html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#30 {main} [] []
```

**Comment by p-maguire** [comment]
@jorgb90 Are you able to provide steps to replicate the logging of this error? I've been unable to replicate this error in a clean installation of Magento 2.4.5.

**Comment by jorgb90** [comment]
@p-maguire No comes by occasionally in our system.log. It doesn't happen with each checkout, so perhaps its admin order instead of customer checkout..
