### ISSUE TITLE
Bitpay v3.0.0.1  Undefined property: stdClass::$data BPRedirect.php on line 133

### ISSUE THREAD

**Issue by villamilmedia** [bitpay/bitpay-checkout-magento2#9]
I've installed the newest version 3.0.0.1 and I have the following error on my Magento 2.3.0 Installation:

1 exception(s):
Exception #0 (Exception): Notice: Undefined property: stdClass::$data in /var/domains/asc-amsterdamseedcenter.com/applicatie/app/code/Bitpay/BPCheckout/Observer/BPRedirect.php on line 133

Exception #0 (Exception): Notice: Undefined property: stdClass::$data in /var/domains/asc-amsterdamseedcenter.com/applicatie/app/code/Bitpay/BPCheckout/Observer/BPRedirect.php on line 133
#0 /var/domains/asc-amsterdamseedcenter.com/applicatie/app/code/Bitpay/BPCheckout/Observer/BPRedirect.php(133): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined prope...', '/var/domains/as...', 133, Array)
#1 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Bitpay\BPCheckout\Observer\BPRedirect->execute(Object(Magento\Framework\Event\Observer))
#2 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Bitpay\BPCheckout\Observer\BPRedirect), Object(Magento\Framework\Event\Observer))
#3 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#4 /var/domains/asc-amsterdamseedcenter.com/applicatie/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('checkout_onepag...', Array)
#5 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/module-checkout/Controller/Onepage/Success.php(29): Magento\Framework\Event\Manager\Proxy->dispatch('checkout_onepag...', Array)
#6 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Controller\Onepage\Success->execute()
#7 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Controller\Onepage\Success\Interceptor->___callParent('execute', Array)
#8 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Controller\Onepage\Success\Interceptor->Magento\Framework\Interception\{closure}()
#9 /var/domains/asc-amsterdamseedcenter.com/applicatie/generated/code/Magento/Checkout/Controller/Onepage/Success/Interceptor.php(26): Magento\Checkout\Controller\Onepage\Success\Interceptor->___callPlugins('execute', Array, Array)
#10 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/App/Action/Action.php(108): Magento\Checkout\Controller\Onepage\Success\Interceptor->execute()
#11 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/module-checkout/Controller/Onepage.php(161): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#12 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Controller\Onepage->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Controller\Onepage\Success\Interceptor->___callParent('dispatch', Array)
#14 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Controller\Onepage\Success\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /var/domains/asc-amsterdamseedcenter.com/applicatie/generated/code/Magento/Checkout/Controller/Onepage/Success/Interceptor.php(39): Magento\Checkout\Controller\Onepage\Success\Interceptor->___callPlugins('dispatch', Array, Array)
#16 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/App/FrontController.php(159): Magento\Checkout\Controller\Onepage\Success\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Checkout\Controller\Onepage\Success\Interceptor))
#18 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#20 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/domains/asc-amsterdamseedcenter.com/applicatie/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#26 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/domains/asc-amsterdamseedcenter.com/applicatie/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#28 /var/domains/asc-amsterdamseedcenter.com/applicatie/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#29 /var/domains/asc-amsterdamseedcenter.com/applicatie/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#30 {main}

**Comment by villamilmedia** [comment]
Issue solved in  v3.0.0.2
